In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("variant_dataset.csv", low_memory=False)

In [3]:
df['genename'] = df['genename'].apply(
    lambda x: ';'.join(sorted(set(x.split(';'))))
)

df = df[df['genename'].apply(lambda x: ';' not in x)]

In [4]:
df["genename"].value_counts()

genename
TTN        3388
FBN1       2358
BRCA2      1851
NF1        1782
KMT2D      1570
           ...
DNAJC11       1
TMEM88B       1
UBL4A         1
OR4F5         1
SMIM9         1
Name: count, Length: 15592, dtype: int64

In [31]:
cancer_genes = [
    "BRCA1", "BRCA2", "TP53", "PTEN", "STK11", "CDH1",
    "PALB2", "CHEK2", "ATM", "BARD1", "BRIP1",
    "RAD51C", "RAD51D", "NBN",

    # Lynch sendromu
    "MLH1", "MSH2", "MSH6", "PMS2", "EPCAM",

    # Kolorektal / polipozis
    "APC", "MUTYH", "SMAD4", "BMPR1A",

    # Diğer sendromlar
    "VHL", "RET", "SDHB", "SDHC", "SDHD", "SDHA",
    "TSC1", "TSC2", "NF1", "NF2",
    "FH", "FLCN", "MET", "BAP1",
    "WT1", "DICER1", "SUFU", "PTCH1"
]

In [32]:
len(cancer_genes)

41

In [33]:
cancer_df = df[df["genename"].isin(cancer_genes)].copy()
cancer_df["genename"].nunique()

41

In [34]:
cancer_df.shape

(19014, 77)

In [23]:
pah_genes = [
    "BMPR2",        # en önemli
    "ACVRL1",       # ALK1
    "ENG",
    "SMAD9",        # SMAD8 olarak da geçebilir
    "CAV1",
    "KCNK3",
    "TBX4",
    "EIF2AK4",

    # daha nadir / yeni genler
    "ATP13A3",
    "SOX17",
    "AQP1",
    "GDF2",
    "KDR"
]

In [24]:
len(pah_genes)

13

In [25]:
pah_df = df[df["genename"].isin(pah_genes)].copy()
pah_df["genename"].nunique()

13

In [12]:
pah_df.shape

(1396, 77)

In [13]:
cftr_genes = ["CFTR"]

In [14]:
cftr_df = df[df["genename"].isin(cftr_genes)].copy()
cftr_df["genename"].nunique()

1

In [15]:
cftr_df.shape

(744, 77)

In [17]:
cancer_df["genename"].value_counts()

genename
BRCA2     1851
NF1       1782
ATM       1417
BRCA1     1396
TSC2       946
MSH2       893
APC        806
MLH1       758
MSH6       628
TP53       596
PTEN       484
VHL        467
PALB2      448
MUTYH      435
PTCH1      427
DICER1     425
PMS2       405
TSC1       391
BRIP1      375
CDH1       324
STK11      309
CHEK2      297
SDHA       296
FH         285
BARD1      261
NBN        248
RAD51C     246
RET        198
BAP1       195
FLCN       180
NF2        173
BMPR1A     163
SMAD4      159
SDHB       158
SDHD       118
WT1        113
SDHC       109
MET         78
SUFU        64
EPCAM       57
RAD51D      53
Name: count, dtype: int64

In [18]:
pah_df["genename"].value_counts()

genename
ENG        480
ACVRL1     367
BMPR2      279
EIF2AK4     69
TBX4        55
CAV1        25
GDF2        23
ATP13A3     18
KDR         18
SMAD9       18
SOX17       16
KCNK3       15
AQP1        13
Name: count, dtype: int64

In [29]:
pah_df["label"].value_counts()

label
1.0    979
0.0    417
Name: count, dtype: int64

In [30]:
cftr_df["label"].value_counts()

label
1.0    711
0.0     33
Name: count, dtype: int64

In [35]:
cancer_df["label"].value_counts()

label
1.0    14689
0.0     4325
Name: count, dtype: int64

In [36]:
df["label"].value_counts()

label
1.0    178926
0.0    167238
Name: count, dtype: int64

In [ ]:
cancer_df.to_csv("cancer_dataset.csv", index=False)

In [ ]:
pah_df.to_csv("pah_dataset.csv", index=False)

In [ ]:
cftr_df.to_csv("cftr_dataset.csv", index=False)